name: Node CI

on: [push]

jobs:
  linux:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.7.0]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: yarn install and dist
      run: |
        yarn
        yarn run dist
      env:
        CI: true
    - name: Upload Artifacts
      uses: actions/upload-artifact@v1.0.0
      with:
        name: ubuntu-build
        path: electron-output/
  
  macos:

    runs-on: macOS-latest

    strategy:
      matrix:
        node-version: [12.7.0]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: yarn install and dist
      run: |
        yarn
        yarn run dist
      env:
        CI: true
    - name: Upload artifacts
      uses: actions/upload-artifact@v1.0.0
      with:
        name: mac-build
        path: electron-output/

  windows:

    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [12.7.0]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: yarn install and dist
      run: |
        yarn
        yarn run dist
      env:
        CI: true
    - name: Upload artifacts
      uses: actions/upload-artifact@v1.0.0
      with:
        name: windows-build
        path: electron-output/
